//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Product()
        {
            this.Table_Sales = new HashSet<Table_Sales>();
        }
    
        public int productID { get; set; }
        public string productName { get; set; }
        public string brand { get; set; }
        public Nullable<short> productCategory { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<byte> stock { get; set; }
    
        public virtual Table_Category Table_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Sales> Table_Sales { get; set; }
    }
}
