//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMVC.Models.Entity
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Customer()
        {
            this.Table_Sales_Deneme = new HashSet<Table_Sales_Deneme>();
            this.Table_Sales = new HashSet<Table_Sales>();
        }
    
        public int customerID { get; set; }
        [Required(ErrorMessage = "Enter Customer Name!")]
        [StringLength(50,ErrorMessage = "You should enter up to 50 characters")]
        public string customerName { get; set; }
        [Required(ErrorMessage = "Enter Customer Lastname")]
        public string customerLname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Sales_Deneme> Table_Sales_Deneme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Sales> Table_Sales { get; set; }
    }
}
