//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Sales
    {
        public int salesID { get; set; }
        public Nullable<int> product { get; set; }
        public Nullable<int> customer { get; set; }
        public Nullable<byte> quantity { get; set; }
        public Nullable<byte> price { get; set; }
    
        public virtual Table_Customer Table_Customer { get; set; }
        public virtual Table_Product Table_Product { get; set; }
    }
}
